### GET /balances/{account_id}

### Consultar saldo da conta da Alice
GET http://localhost:3003/balances/0c4d1f7b-3b34-4461-9b21-76e58f7b6db8 HTTP/1.1
Content-Type: application/json


### Consultar saldo da conta da Maria Souza
GET http://localhost:3003/balances/17ca1194-28da-413a-8136-b4b700b6b13f HTTP/1.1
Content-Type: application/json


